variable "folder_path" {
  description = "The path to the open next artifacts"
  type        = string
}

variable "zone_suffix" {
  description = "An optional zone suffix to add to the assets and cache folder to allow files to be loaded correctly"
  type        = string
  default     = null
}

variable "s3_exclusion_regex" {
  description = "A regex of files to exclude from the s3 copy"
  type        = string
  default     = null
}

variable "cache_control_immutable_assets_regex" {
  description = "Regex to set public,max-age=31536000,immutable on immutable resources"
  type        = string
  default     = "^.*(\\.next)$"
}

variable "force_destroy" {
  description = "Whether to force destroy the bucket and associated resources"
  type        = bool
  default     = false
}

variable "remove_folder" {
  description = "Whether to delete the folder before uploading assets"
  type        = bool
}

variable "s3_path_prefix" {
  description = "The path to add all the files under"
  type        = string
}

variable "content_types" {
  description = "The MIME type mapping and default for artefacts generated by Open Next"
  type = object({
    mapping = optional(map(string), {
      "svg"  = "image/svg+xml",
      "js"   = "application/javascript",
      "css"  = "text/css",
      "html" = "text/html",
    })
    default = optional(string, "binary/octet-stream")
  })
  default = {}
}

variable "bucket_name" {
  description = "The name of the bucket to upload files to"
  type        = string
}

variable "additional_files" {
  description = "Allow additional files to be uploaded to the bucket. All files will be added as per the s3_path_prefix"
  type = list(object({
    name        = string
    source      = string
    path_prefix = string
  }))
  default = []
}
